# Generated by Django 4.2.7 on 2023-12-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
