# Generated by Django 4.2.7 on 2023-12-11 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_full_name_profile_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(default=1377922, max_length=1000)),
                ('balance', models.CharField(default='0', max_length=1000)),
                ('overdraftLimit', models.CharField(default=1000, max_length=1000)),
                ('acountType', models.CharField(choices=[('checkings', 'Checkings'), ('savings', 'Savings'), ('credit card', 'Credit Card'), ('loan', 'Loan')], default='checkings')),
                ('interestRate', models.CharField(default=0.05, max_length=1000)),
                ('creditLimit', models.CharField(default=1000, max_length=1000)),
                ('minimumPayment', models.CharField(default=0, max_length=1000)),
                ('paymentDueDate', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
