# Generated by Django 4.2.7 on 2023-12-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(default=8484662, max_length=1000),
        ),
        migrations.AlterField(
            model_name='account',
            name='paymentDueDate',
            field=models.DateTimeField(),
        ),
    ]
