# Generated by Django 4.2.7 on 2023-12-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_account_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(default=8020399, max_length=1000),
        ),
        migrations.AlterField(
            model_name='account',
            name='paymentDueDate',
            field=models.DateTimeField(default=0),
        ),
    ]
