# Generated by Django 4.2.7 on 2023-12-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_account_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(default=2091574, max_length=1000),
        ),
    ]
