# Generated by Django 4.2.7 on 2023-12-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_account_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(default=1122489, max_length=1000),
        ),
        migrations.AlterField(
            model_name='account',
            name='paymentDueDate',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
