# Generated by Django 4.2.7 on 2023-12-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_account_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(default=9768269, max_length=1000),
        ),
        migrations.AlterField(
            model_name='account',
            name='acountType',
            field=models.CharField(choices=[('Checkings', 'Checkings'), ('Savings', 'Savings'), ('Credit Card', 'Credit Card'), ('Loan', 'Loan')], default='checkings'),
        ),
    ]
